version: '3.9'
services:
  app:
    container_name: nebula-api-app
    build: 
      context: .
      dockerfile: .docker/api/Dockerfile
    expose:
      - 3000
    depends_on:
      - mongo
      - redis
  nginx:
    depends_on:
      - app
    volumes:
      - ./.docker/nginx/conf.d/staging/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs:/var/log/nginx
