version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nebula-api-nginx
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./.docker/nginx/conf.d/dev/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs:/var/log/nginx
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    container_name: nebula-api-mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbData:/data/db
  redis:
    image: redis:latest
    container_name: nebula-api-redis
    ports:
      - 6379:6379
    volumes:
      - redisData:/data

volumes:
  mongodbData:
  redisData: