const ApiCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_NAME_TAKEN: 'USER_NAME_TAKEN',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_CURRENT_PASSWORD_INVALID: 'USER_CURRENT_PASSWORD_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  VERIFICATION_TOKEN_INVALID: 'VERIFICATION_TOKEN_INVALID',
  VERiFICATION_TOKEN_EXPIRED: 'VERiFICATION_TOKEN_EXPIRED',
  LOGIN_INVALID_CREDENTIAL: 'LOGIN_INVALID_CREDENTIAL',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID'
};

module.exports = {
  ApiCode
};